/// DevTunnelsBridge — Dev Tunnels connectivity for Swift.
///
/// This package wraps the Microsoft Dev Tunnels Rust SDK via UniFFI,
/// providing tunnel discovery, authentication, and relay connections
/// for iOS and macOS apps.
///
/// ## Quick Start
///
/// ```swift
/// let tunnels = try listTunnels(accessToken: "ghp_...")
/// print(tunnels.map { $0.name })
/// ```
///
/// The public API is generated by UniFFI from the Rust source.
/// See Generated/DevTunnelsFFI.swift for the full API surface.
///
/// Key types (from UniFFI):
/// - `TunnelInfo` — Tunnel metadata (tunnelId, name, clusterId, hasEndpoints)
/// - `TunnelError` — Error enum (authenticationFailed, noTunnelsFound, apiError)
/// - `listTunnels(accessToken:)` — List all tunnels for the authenticated user

