// Hand-written wire helper. Not regenerated by `npm run generate:dotnet`.
#nullable enable

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Microsoft.AgentHostProtocol;

/// <summary>
/// A wire value that may be either a plain JSON string or an object of the
/// form <c>{ "markdown": "..." }</c>. The wrapper preserves which form was
/// decoded so that re-encoding round-trips faithfully. The default (empty)
/// value encodes as the empty string <c>""</c>.
/// </summary>
[JsonConverter(typeof(StringOrMarkdownConverter))]
public sealed class StringOrMarkdown
{
    /// <summary>
    /// Non-null iff the value was decoded from the <c>{ "markdown": "..." }</c>
    /// object form.
    /// </summary>
    public string? Markdown { get; init; }

    /// <summary>Non-null iff the value was decoded from a bare JSON string.</summary>
    public string? Plain { get; init; }

    /// <summary>Creates an empty value (encodes as <c>""</c>).</summary>
    public StringOrMarkdown()
    {
    }

    /// <summary>Returns a value that encodes as a bare JSON string.</summary>
    public static StringOrMarkdown FromPlain(string text) => new() { Plain = text };

    /// <summary>Returns a value that encodes as <c>{ "markdown": text }</c>.</summary>
    public static StringOrMarkdown FromMarkdown(string text) => new() { Markdown = text };

    /// <summary>
    /// Returns the underlying text regardless of which form the value was
    /// decoded from. Returns the empty string for the empty value.
    /// </summary>
    public string AsText() => Plain ?? Markdown ?? string.Empty;
}

/// <summary>System.Text.Json converter for <see cref="StringOrMarkdown"/>.</summary>
internal sealed class StringOrMarkdownConverter : JsonConverter<StringOrMarkdown>
{
    /// <inheritdoc />
    public override StringOrMarkdown Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
    {
        switch (reader.TokenType)
        {
            case JsonTokenType.Null:
                return new StringOrMarkdown();
            case JsonTokenType.String:
                return new StringOrMarkdown { Plain = reader.GetString() };
            default:
                using (JsonDocument doc = JsonDocument.ParseValue(ref reader))
                {
                    if (doc.RootElement.ValueKind == JsonValueKind.Object
                        && doc.RootElement.TryGetProperty("markdown", out JsonElement md)
                        && md.ValueKind == JsonValueKind.String)
                    {
                        return new StringOrMarkdown { Markdown = md.GetString() };
                    }

                    throw new JsonException("StringOrMarkdown object form missing required 'markdown' field");
                }
        }
    }

    /// <inheritdoc />
    public override void Write(Utf8JsonWriter writer, StringOrMarkdown value, JsonSerializerOptions options)
    {
        if (value.Plain is not null)
        {
            writer.WriteStringValue(value.Plain);
            return;
        }

        if (value.Markdown is not null)
        {
            writer.WriteStartObject();
            writer.WriteString("markdown", value.Markdown);
            writer.WriteEndObject();
            return;
        }

        writer.WriteStringValue(string.Empty);
    }
}
