// Hand-written generic converter shared by every generated discriminated
// union. Not regenerated by `npm run generate:dotnet`.
#nullable enable

using System;
using System.Collections.Generic;
using System.Diagnostics.CodeAnalysis;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Microsoft.AgentHostProtocol;

/// <summary>
/// System.Text.Json converter base for discriminated unions whose variant is
/// selected by a string-valued discriminator field. The generated code
/// supplies the discriminator field name and the wire-value → CLR-type map
/// via a tiny subclass; all of the read/write logic lives here.
/// </summary>
/// <typeparam name="T">The generated union wrapper type.</typeparam>
public abstract class UnionConverter<T> : JsonConverter<T>
    where T : AhpUnion, new()
{
    private readonly string _discriminator;
    private readonly IReadOnlyDictionary<string, Type> _variants;
    private readonly bool _allowUnknown;

    /// <summary>Creates a union converter.</summary>
    /// <param name="discriminator">The JSON field that selects the variant.</param>
    /// <param name="variants">Map from discriminator wire value to CLR payload type.</param>
    /// <param name="allowUnknown">
    /// When <see langword="true"/>, an unrecognized discriminator value is
    /// preserved as a raw <see cref="JsonElement"/> rather than throwing.
    /// </param>
    protected UnionConverter(
        string discriminator,
        IReadOnlyDictionary<string, Type> variants,
        bool allowUnknown)
    {
        _discriminator = discriminator;
        _variants = variants;
        _allowUnknown = allowUnknown;
    }

    /// <inheritdoc />
    // root.Deserialize(variantType, options) resolves the payload type at runtime
    // from the variant map — genuinely trim/AOT-unsafe. The unsafety is already
    // declared on the public contract (IAhpSerializer is [RequiresUnreferencedCode]/
    // [RequiresDynamicCode]); this converter is reachable ONLY through that
    // serializer. JsonConverter<T>.Read in the base is not annotated, so the
    // requirement cannot be re-declared via [RequiresUnreferencedCode] here (it
    // would trip IL2046) — the suppression points back to the contract that owns it.
    [UnconditionalSuppressMessage("Trimming", "IL2026",
        Justification = "Reached only via the [RequiresUnreferencedCode] IAhpSerializer; the base JsonConverter<T>.Read cannot carry the attribute.")]
    [UnconditionalSuppressMessage("AOT", "IL3050",
        Justification = "Reached only via the [RequiresDynamicCode] IAhpSerializer; the base JsonConverter<T>.Read cannot carry the attribute.")]
    public override T? Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
    {
        if (reader.TokenType == JsonTokenType.Null)
        {
            return null;
        }

        using JsonDocument doc = JsonDocument.ParseValue(ref reader);
        JsonElement root = doc.RootElement;

        string? disc = null;
        if (root.ValueKind == JsonValueKind.Object
            && root.TryGetProperty(_discriminator, out JsonElement discElement)
            && discElement.ValueKind == JsonValueKind.String)
        {
            disc = discElement.GetString();
        }

        var result = new T();
        if (disc is not null && _variants.TryGetValue(disc, out Type? variantType))
        {
            result.Value = root.Deserialize(variantType, options);
        }
        else if (_allowUnknown)
        {
            // Preserve the original JSON verbatim for loss-free round-trips.
            result.Value = root.Clone();
        }
        else
        {
            throw new JsonException(
                $"Unknown {typeof(T).Name} discriminator '{disc}' (field '{_discriminator}')");
        }

        return result;
    }

    /// <inheritdoc />
    // JsonSerializer.Serialize(writer, inner, inner.GetType(), options) serializes
    // by the boxed runtime type — genuinely trim/AOT-unsafe, for the same reason
    // as Read above. Declared on the IAhpSerializer contract; suppressed here
    // because the base JsonConverter<T>.Write is not annotated.
    [UnconditionalSuppressMessage("Trimming", "IL2026",
        Justification = "Reached only via the [RequiresUnreferencedCode] IAhpSerializer; the base JsonConverter<T>.Write cannot carry the attribute.")]
    [UnconditionalSuppressMessage("AOT", "IL3050",
        Justification = "Reached only via the [RequiresDynamicCode] IAhpSerializer; the base JsonConverter<T>.Write cannot carry the attribute.")]
    public override void Write(Utf8JsonWriter writer, T value, JsonSerializerOptions options)
    {
        object? inner = value?.Value;
        if (inner is null)
        {
            writer.WriteNullValue();
            return;
        }

        if (inner is JsonElement raw)
        {
            // Unknown variant — emit the preserved JSON exactly as received.
            raw.WriteTo(writer);
            return;
        }

        // Serialize by the runtime type so every property (including the
        // variant's own discriminator field) is written.
        JsonSerializer.Serialize(writer, inner, inner.GetType(), options);
    }
}
