// Hand-written support for string-valued protocol enums whose wire form does
// not match the C# member name (e.g. "single-select", "pending-confirmation",
// "session/delta"). Not regenerated by `npm run generate:dotnet`.
#nullable enable

using System;
using System.Collections.Generic;
using System.Diagnostics.CodeAnalysis;
using System.Reflection;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Microsoft.AgentHostProtocol;

/// <summary>
/// Declares the exact wire string for an enum member when it differs from the
/// member's C# name. Consumed by <see cref="WireEnumConverter{T}"/>.
/// </summary>
[AttributeUsage(AttributeTargets.Field, AllowMultiple = false)]
public sealed class WireValueAttribute : Attribute
{
    /// <summary>The wire string for the annotated enum member.</summary>
    public string Value { get; }

    /// <summary>Creates a <see cref="WireValueAttribute"/>.</summary>
    /// <param name="value">The wire string.</param>
    public WireValueAttribute(string value)
    {
        Value = value;
    }
}

/// <summary>
/// System.Text.Json converter that (de)serializes a string-valued protocol
/// enum using the <see cref="WireValueAttribute"/> on each member (falling
/// back to the member name when the attribute is absent).
/// </summary>
/// <typeparam name="T">The enum type.</typeparam>
public sealed class WireEnumConverter<
    [DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.PublicFields)] T> : JsonConverter<T>
    where T : struct, Enum
{
    private static readonly Dictionary<T, string> s_toWire;
    private static readonly Dictionary<string, T> s_fromWire;

    static WireEnumConverter()
    {
        var toWire = new Dictionary<T, string>();
        var fromWire = new Dictionary<string, T>(StringComparer.Ordinal);
        foreach (FieldInfo field in typeof(T).GetFields(BindingFlags.Public | BindingFlags.Static))
        {
            var value = (T)field.GetValue(null)!;
            string wire = field.GetCustomAttribute<WireValueAttribute>()?.Value ?? field.Name;
            toWire[value] = wire;
            fromWire[wire] = value;
        }

        s_toWire = toWire;
        s_fromWire = fromWire;
    }

    /// <inheritdoc />
    public override T Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
    {
        string? wire = reader.GetString();
        if (wire is not null && s_fromWire.TryGetValue(wire, out T value))
        {
            return value;
        }

        throw new JsonException($"Unknown {typeof(T).Name} wire value '{wire}'");
    }

    /// <inheritdoc />
    public override void Write(Utf8JsonWriter writer, T value, JsonSerializerOptions options)
    {
        if (s_toWire.TryGetValue(value, out string? wire))
        {
            writer.WriteStringValue(wire);
            return;
        }

        throw new JsonException($"Unmapped {typeof(T).Name} value '{value}'");
    }
}
