/**
 * C# / .NET Generator — Generates C# type definitions for the
 * `Microsoft.AgentHostProtocol.Abstractions` package from the
 * TypeScript source of truth parsed via ts-morph.
 *
 * Output: clients/dotnet/src/AgentHostProtocol.Abstractions/Generated/
 *   {State,Actions,Commands,Notifications,Errors,Messages,Version}.generated.cs
 *
 * Mirrors the structure of `generate-go.ts` — the curated struct / enum /
 * union lists are identical because they are protocol-driven, not
 * language-driven. Only the emit functions differ. The generated files
 * are always overwritten; the hand-written files under `Common/` and the
 * interface seams (`ITransport`, `IAhpSerializer`) are left alone.
 *
 * Conventions:
 *   - Wire field names (camelCase) are preserved exactly via
 *     `[JsonPropertyName("...")]`. C# property identifiers are PascalCase.
 *   - Required fields → non-nullable, always serialized.
 *   - Optional fields → nullable (`T?`) + `[JsonIgnore(Condition =
 *     JsonIgnoreCondition.WhenWritingNull)]`.
 *   - TS `number` → C# `long` unless `@format float` → `double`.
 *   - TS `unknown` / `object` → `JsonElement`; `Record<string, unknown>`
 *     → `Dictionary<string, JsonElement>`.
 *   - Discriminated unions are emitted as a sealed wrapper class deriving
 *     from `AhpUnion` (a hand-written base carrying `object? Value`) plus
 *     a generated `UnionConverter<T>` subclass. Unknown discriminator
 *     values surface as a raw `JsonElement` stored in `Value`, preserved
 *     verbatim for loss-free round-trips.
 *   - String enums map wire values via `[WireValue("...")]` + the
 *     hand-written `WireEnumConverter<T>`. Bitset enums (numeric values)
 *     become `[Flags] enum : uint` and serialize as their numeric value
 *     (System.Text.Json default), so unknown future bits round-trip.
 */

import {
  Project,
  InterfaceDeclaration,
  EnumDeclaration,
  PropertySignature,
} from 'ts-morph';
import fs from 'fs';
import path from 'path';
import { findProtocolSourceFiles } from './find-protocol-sources.js';
import { readProtocolVersions } from './read-protocol-versions.js';

const NAMESPACE = 'Microsoft.AgentHostProtocol';

function fileHeader(extraUsings: string[] = []): string {
  const usings = [
    'using System;',
    'using System.Collections.Generic;',
    'using System.Text.Json;',
    'using System.Text.Json.Serialization;',
    ...extraUsings,
  ];
  return (
    '// <auto-generated>\n' +
    '// Generated from types/*.ts — do not edit.\n' +
    '//\n' +
    '// Regenerate with: npm run generate:dotnet\n' +
    '// </auto-generated>\n' +
    '#nullable enable\n\n' +
    usings.join('\n') +
    '\n\n' +
    `namespace ${NAMESPACE};\n`
  );
}

// ─── Name Mapping ────────────────────────────────────────────────────────────

/** Strips the I prefix from interface names: IRootState → RootState */
function stripIPrefix(tsName: string): string {
  if (
    tsName.length > 1 &&
    tsName[0] === 'I' &&
    tsName[1] === tsName[1].toUpperCase() &&
    tsName[1] !== tsName[1].toLowerCase()
  ) {
    return tsName.substring(1);
  }
  return tsName;
}

const CS_RESERVED = new Set([
  'abstract', 'as', 'base', 'bool', 'break', 'byte', 'case', 'catch', 'char',
  'checked', 'class', 'const', 'continue', 'decimal', 'default', 'delegate',
  'do', 'double', 'else', 'enum', 'event', 'explicit', 'extern', 'false',
  'finally', 'fixed', 'float', 'for', 'foreach', 'goto', 'if', 'implicit',
  'in', 'int', 'interface', 'internal', 'is', 'lock', 'long', 'namespace',
  'new', 'null', 'object', 'operator', 'out', 'override', 'params', 'private',
  'protected', 'public', 'readonly', 'ref', 'return', 'sbyte', 'sealed',
  'short', 'sizeof', 'stackalloc', 'static', 'string', 'struct', 'switch',
  'this', 'throw', 'true', 'try', 'typeof', 'uint', 'ulong', 'unchecked',
  'unsafe', 'ushort', 'using', 'virtual', 'void', 'volatile', 'while',
]);

/** Escape a C# identifier that collides with a keyword via the `@` prefix. */
function csIdent(name: string): string {
  return CS_RESERVED.has(name) ? `@${name}` : name;
}

/** camelCase/snake_case/whatever → PascalCase. */
function toPascalCase(name: string): string {
  if (!name) return name;
  const cleaned = name.replace(/^_+/, '');
  const segments = cleaned.split(/[_-]/).filter(Boolean);
  if (segments.length > 1) {
    return segments.map((s) => s[0].toUpperCase() + s.slice(1)).join('');
  }
  return cleaned[0].toUpperCase() + cleaned.slice(1);
}

/** PascalCase enum-variant name from a free-form string. */
function toEnumVariant(value: string): string {
  const cleaned = value.replace(/[^a-zA-Z0-9]+/g, ' ').trim();
  return cleaned
    .split(' ')
    .filter(Boolean)
    .map((w) => w[0].toUpperCase() + w.slice(1))
    .join('');
}

// ─── Type Mapping ────────────────────────────────────────────────────────────

const requiredPartialStructs = new Set<string>();

function partialCsName(tsInterfaceName: string): string {
  return `Partial${stripIPrefix(tsInterfaceName)}`;
}

/** Map a TypeScript type expression to a C# type expression (no nullability). */
function mapType(tsType: string): string {
  tsType = tsType.replace(/import\([^)]+\)\./g, '').trim();

  while (tsType.startsWith('(') && tsType.endsWith(')')) {
    tsType = tsType.slice(1, -1).trim();
  }

  if (tsType === 'string') return 'string';
  if (tsType === 'number') return 'long';
  if (tsType === 'boolean') return 'bool';
  if (tsType === 'unknown') return 'JsonElement';
  if (tsType === 'object') return 'JsonElement';
  if (tsType === 'true' || tsType === 'false') return 'bool';

  if (tsType === 'URI') return 'string';
  if (tsType === 'StringOrMarkdown') return 'StringOrMarkdown';

  // ChildCustomizationType is a TS-only subset alias of CustomizationType.
  if (tsType === 'ChildCustomizationType') return 'CustomizationType';

  if (tsType === 'SessionStatus') return 'SessionStatus';

  if (
    tsType === 'IRootState | ISessionState' ||
    tsType === 'IRootState | ISessionState | ITerminalState' ||
    tsType === 'RootState | SessionState' ||
    tsType === 'RootState | SessionState | TerminalState' ||
    tsType === 'RootState | SessionState | TerminalState | ChangesetState'
  ) {
    return 'SnapshotState';
  }

  // `T | null` — handled at the property level (nullability); strip here.
  const nullMatch = tsType.match(/^(.+?)\s*\|\s*null$/);
  if (nullMatch) {
    return mapType(nullMatch[1]);
  }

  const undefMatch = tsType.match(/^(.+?)\s*\|\s*undefined$/);
  if (undefMatch) return mapType(undefMatch[1]);

  const arrayMatch = tsType.match(/^(.+)\[\]$/);
  if (arrayMatch) return `List<${mapType(arrayMatch[1])}>`;

  const arrayGenericMatch = tsType.match(/^Array<(.+)>$/);
  if (arrayGenericMatch) return `List<${mapType(arrayGenericMatch[1])}>`;

  const recordMatch = tsType.match(/^Record<string,\s*(.+)>$/);
  if (recordMatch) {
    const inner = recordMatch[1].trim();
    if (inner === 'unknown') return 'Dictionary<string, JsonElement>';
    return `Dictionary<string, ${mapType(inner)}>`;
  }

  const partialMatch = tsType.match(/^Partial<(\w+)>$/);
  if (partialMatch) {
    requiredPartialStructs.add(partialMatch[1]);
    return partialCsName(partialMatch[1]);
  }

  const enumUnionMatch = tsType.match(/^(\w+)\.\w+(\s*\|\s*\1\.\w+)*$/);
  if (enumUnionMatch) return stripIPrefix(enumUnionMatch[1]);

  const enumMemberMatch = tsType.match(/^(\w+)\.(\w+)$/);
  if (enumMemberMatch) return stripIPrefix(enumMemberMatch[1]);

  if (tsType.startsWith("'") && tsType.endsWith("'")) return 'string';
  if (/^'[^']*'(\s*\|\s*'[^']*')+$/.test(tsType)) return 'string';

  if (tsType.startsWith('{')) return 'JsonElement';

  return stripIPrefix(tsType);
}

// Value-type detection lives in `csIsValueType` below; it consults the
// `ALL_ENUM_NAMES` set so optional enum-typed properties get a `?`.

// ─── Property Extraction ─────────────────────────────────────────────────────

interface CsProp {
  csName: string;
  wireName: string;
  csType: string;
  optional: boolean;
  doc: string;
  isLiteralDiscriminant: boolean;
  literalValue?: string;
}

function getPropertyType(prop: PropertySignature): string {
  const typeNode = prop.getTypeNode();
  if (typeNode) return typeNode.getText();
  return prop.getType().getText(prop);
}

function getPropertyDoc(prop: PropertySignature): string {
  const jsDocs = prop.getJsDocs();
  if (jsDocs.length === 0) return '';
  return jsDocs[0].getDescription().trim();
}

function hasFormatFloat(prop: PropertySignature): boolean {
  for (const doc of prop.getJsDocs()) {
    for (const tag of doc.getTags()) {
      if (tag.getTagName() === 'format' && tag.getCommentText()?.trim() === 'float') {
        return true;
      }
    }
  }
  return false;
}

function getAllProperties(iface: InterfaceDeclaration, project: Project): PropertySignature[] {
  const props: PropertySignature[] = [];
  for (const ext of iface.getExtends()) {
    const baseName = ext.getExpression().getText();
    const baseIface = findInterface(project, baseName);
    if (baseIface) {
      props.push(...getAllProperties(baseIface, project));
    }
  }
  props.push(...iface.getProperties());
  return props;
}

function findInterface(project: Project, name: string): InterfaceDeclaration | undefined {
  for (const sf of project.getSourceFiles()) {
    const iface = sf.getInterface(name);
    if (iface) return iface;
  }
  return undefined;
}

function findEnum(project: Project, name: string): EnumDeclaration | undefined {
  for (const sf of project.getSourceFiles()) {
    const e = sf.getEnum(name);
    if (e) return e;
  }
  return undefined;
}

/** Names of every enum the generator emits (so optionals can nullable-ify value-type enums). */
const ALL_ENUM_NAMES = new Set<string>();

function extractProps(iface: InterfaceDeclaration, project: Project): CsProp[] {
  const allProps = getAllProperties(iface, project);
  const seen = new Set<string>();
  const result: CsProp[] = [];

  for (const p of allProps) {
    const tsName = p.getName();
    if (seen.has(tsName)) continue;
    seen.add(tsName);

    const tsType = getPropertyType(p);

    const enumMember = tsType.match(/^(\w+)\.(\w+)$/);
    const stringLiteral = tsType.match(/^'([^']+)'$/);
    let isLiteralDiscriminant = false;
    let literalValue: string | undefined;

    const tsPropLower = tsName.toLowerCase();
    if (['type', 'kind', 'status', 'state'].includes(tsPropLower)) {
      if (enumMember) {
        const enumName = enumMember[1];
        const memberName = enumMember[2];
        const enumDecl = findEnum(project, enumName);
        if (enumDecl) {
          const mem = enumDecl.getMembers().find((m) => m.getName() === memberName);
          if (mem) {
            isLiteralDiscriminant = true;
            literalValue = String(mem.getValue());
          }
        }
      } else if (stringLiteral) {
        isLiteralDiscriminant = true;
        literalValue = stringLiteral[1];
      } else if (/^\w+\.\w+(\s*\|\s*\w+\.\w+)+$/.test(tsType)) {
        isLiteralDiscriminant = true;
      }
    }

    const csName = csIdent(toPascalCase(tsName));
    const hasUnionUndefined = /\|\s*undefined/.test(tsType);
    const hasUnionNull = /\|\s*null/.test(tsType);
    const hasQuestionToken = p.hasQuestionToken();

    let csType = mapType(tsType);
    if (csType === 'long' && hasFormatFloat(p)) {
      csType = 'double';
    }

    const optional = hasQuestionToken || hasUnionUndefined || hasUnionNull;

    result.push({
      csName,
      wireName: tsName,
      csType,
      optional,
      doc: getPropertyDoc(p),
      isLiteralDiscriminant,
      literalValue,
    });
  }
  return result;
}

/** True when the C# type is a value type (primitive / JsonElement / known enum). */
function csIsValueType(csType: string): boolean {
  if (csType === 'long' || csType === 'double' || csType === 'bool' || csType === 'JsonElement') {
    return true;
  }
  return ALL_ENUM_NAMES.has(csType);
}

// ─── Doc Comments ────────────────────────────────────────────────────────────

function emitDocComment(prefix: string, doc: string | undefined, lines: string[]): void {
  if (!doc) return;
  const docLines = doc.split('\n').map((l) => l.trimEnd());
  // Trim trailing blank lines.
  while (docLines.length && docLines[docLines.length - 1] === '') docLines.pop();
  if (docLines.length === 0) return;
  lines.push(`${prefix}/// <summary>`);
  for (const line of docLines) {
    lines.push(`${prefix}/// ${escapeXmlDoc(line)}`.trimEnd());
  }
  lines.push(`${prefix}/// </summary>`);
}

function escapeXmlDoc(s: string): string {
  return s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
}

// ─── Enum Generation ─────────────────────────────────────────────────────────

/**
 * String enum:
 *   [JsonConverter(typeof(WireEnumConverter<PolicyState>))]
 *   public enum PolicyState { [WireValue("enabled")] Enabled, ... }
 */
function generateStringEnum(enumDecl: EnumDeclaration): string {
  const name = enumDecl.getName();
  const lines: string[] = [];
  emitDocComment('', enumDecl.getJsDocs()[0]?.getDescription().trim(), lines);
  lines.push(`[JsonConverter(typeof(WireEnumConverter<${name}>))]`);
  lines.push(`public enum ${name}`);
  lines.push('{');
  const members = enumDecl.getMembers();
  members.forEach((mem) => {
    const memberDoc = mem.getJsDocs()[0]?.getDescription().trim();
    emitDocComment('    ', memberDoc, lines);
    const wire = String(mem.getValue());
    lines.push(`    [WireValue(${JSON.stringify(wire)})]`);
    lines.push(`    ${mem.getName()},`);
  });
  lines.push('}');
  return lines.join('\n');
}

/**
 * Bitset enum (numeric values): [Flags] enum : uint. System.Text.Json
 * serializes enums as their numeric value by default, so unknown future
 * bits round-trip losslessly.
 */
function generateBitsetEnum(enumDecl: EnumDeclaration): string {
  const name = enumDecl.getName();
  const lines: string[] = [];
  emitDocComment('', enumDecl.getJsDocs()[0]?.getDescription().trim(), lines);
  lines.push('[Flags]');
  lines.push(`public enum ${name} : uint`);
  lines.push('{');
  for (const mem of enumDecl.getMembers()) {
    const memberDoc = mem.getJsDocs()[0]?.getDescription().trim();
    emitDocComment('    ', memberDoc, lines);
    lines.push(`    ${mem.getName()} = ${mem.getValue()},`);
  }
  lines.push('}');
  return lines.join('\n');
}

function generateEnum(enumDecl: EnumDeclaration): string {
  const values = enumDecl.getMembers().map((m) => m.getValue());
  const isNumeric = values.every((v) => typeof v === 'number');
  return isNumeric ? generateBitsetEnum(enumDecl) : generateStringEnum(enumDecl);
}

// ─── Struct Generation ───────────────────────────────────────────────────────

interface StructOpts {
  omitDiscriminants?: boolean;
  doc?: string;
  includeDiscriminants?: boolean;
}

/** True when the C# type is a generic collection the generator emits
 *  (`List<...>` / `Dictionary<...>`). A required-but-unset collection is
 *  modeled as null-forgiving (see {@link csPropDefault}). */
function csIsCollectionType(csType: string): boolean {
  return csType.startsWith('List<') || csType.startsWith('Dictionary<');
}

/**
 * True when a REQUIRED property is a nested object — i.e. a reference type that
 * is neither a string, a StringOrMarkdown wrapper, a value type/enum, nor a
 * generic collection. The schema marks these `required`, so the C# field must
 * be non-nullable AND enforced on decode. We model that with the C# `required`
 * modifier (see {@link csRequiredModifier}) rather than a null-forgiving
 * default, so a wire payload omitting the field is rejected — matching the
 * schema's `required` array (e.g. SessionAddedParams.summary). Collections keep
 * the null-forgiving default because a null collection serializes as `null`,
 * which the conformance harness strips (matching Go's nil slice/map).
 */
function csIsRequiredNestedObject(csType: string, optional: boolean): boolean {
  if (optional) return false;
  if (csIsValueType(csType)) return false;
  if (csType === 'string' || csType === 'StringOrMarkdown') return false;
  if (csIsCollectionType(csType)) return false;
  return true;
}

/** The `required ` modifier (with trailing space) for properties that must be
 *  set, else the empty string. */
function csRequiredModifier(csType: string, optional: boolean): string {
  return csIsRequiredNestedObject(csType, optional) ? 'required ' : '';
}

function csPropDefault(csType: string, optional: boolean): string {
  if (optional) return '';
  // Required value types get the C# default (matches Go's numeric/bool zero).
  if (csIsValueType(csType)) return '';
  // Required string → "" (matches Go's string zero value, which serializes
  // as "" rather than null).
  if (csType === 'string') return ' = "";';
  // Required StringOrMarkdown → empty wrapper, which serializes as "" (matches
  // Go's value-type zero).
  if (csType === 'StringOrMarkdown') return ' = new();';
  // Required nested objects use the `required` modifier (no default) so a wire
  // payload missing the field is rejected, matching the schema's `required`
  // array. csRequiredModifier emits the keyword; no initializer is needed.
  if (csIsRequiredNestedObject(csType, optional)) return '';
  // Required collections → null-forgiving. A null collection serializes as
  // `null`, which the conformance harness strips — matching Go, where a
  // required-but-unset slice/map is `nil` → `null`. Deserialization and
  // reducers populate these before they are read.
  return ' = null!;';
}

function generateCsClass(csName: string, props: CsProp[], opts: StructOpts = {}): string {
  const lines: string[] = [];
  emitDocComment('', opts.doc, lines);
  const include = opts.includeDiscriminants === true;
  const emittedProps = props.filter(
    (p) => include || !(opts.omitDiscriminants && p.isLiteralDiscriminant),
  );

  lines.push(`public sealed class ${csName}`);
  lines.push('{');
  emittedProps.forEach((p, idx) => {
    if (idx > 0) lines.push('');
    if (p.doc) emitDocComment('    ', p.doc, lines);
    lines.push(`    [JsonPropertyName(${JSON.stringify(p.wireName)})]`);
    let csType = p.csType;
    if (p.optional) {
      lines.push('    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]');
      csType = `${csType}?`;
    }
    const def = csPropDefault(p.csType, p.optional);
    const req = csRequiredModifier(p.csType, p.optional);
    lines.push(`    public ${req}${csType} ${p.csName} { get; set; }${def}`);
  });
  lines.push('}');
  return lines.join('\n');
}

function generateClassFromInterface(
  project: Project,
  tsInterfaceName: string,
  csNameOverride?: string,
  opts: StructOpts = {},
): string {
  const iface = findInterface(project, tsInterfaceName);
  if (!iface) throw new Error(`Interface ${tsInterfaceName} not found`);
  const name = csNameOverride ?? stripIPrefix(tsInterfaceName);
  const props = extractProps(iface, project);
  const ifaceDoc = iface.getJsDocs()[0]?.getDescription().trim();
  return generateCsClass(name, props, { doc: ifaceDoc, ...opts });
}

function generatePartialClass(project: Project, tsInterfaceName: string): string {
  const iface = findInterface(project, tsInterfaceName);
  if (!iface) throw new Error(`Interface ${tsInterfaceName} not found`);
  const props = extractProps(iface, project).map((p) => ({ ...p, optional: true }));
  return generateCsClass(partialCsName(tsInterfaceName), props, {
    doc: `Partial equivalent of ${stripIPrefix(tsInterfaceName)} — every field is optional for delta updates.`,
  });
}

// ─── Discriminated Union Generation ──────────────────────────────────────────

interface UnionVariant {
  variantName: string;
  innerType: string;
  wireValue: string;
  doc?: string;
}

interface UnionConfig {
  name: string;
  discriminantField: string;
  doc?: string;
  variants: UnionVariant[];
  unknown?: boolean;
}

function generateDiscriminatedUnion(cfg: UnionConfig): string {
  const lines: string[] = [];
  emitDocComment('', cfg.doc, lines);
  lines.push(`[JsonConverter(typeof(${cfg.name}Converter))]`);
  lines.push(`public sealed class ${cfg.name} : AhpUnion`);
  lines.push('{');
  lines.push(`    /// <summary>Creates an empty ${cfg.name} (no active variant).</summary>`);
  lines.push(`    public ${cfg.name}() { }`);
  lines.push('');
  lines.push(`    /// <summary>Creates a ${cfg.name} wrapping the given variant value.</summary>`);
  lines.push(`    public ${cfg.name}(object? value) : base(value) { }`);
  lines.push('}');
  lines.push('');

  // Converter
  const entries = cfg.variants
    .map((v) => `        [${JSON.stringify(v.wireValue)}] = typeof(${v.innerType}),`)
    .join('\n');
  lines.push(
    `/// <summary>System.Text.Json converter for the ${cfg.name} discriminated union.</summary>`,
  );
  lines.push(`internal sealed class ${cfg.name}Converter : UnionConverter<${cfg.name}>`);
  lines.push('{');
  lines.push(`    public ${cfg.name}Converter()`);
  lines.push(`        : base(`);
  lines.push(`            discriminator: ${JSON.stringify(cfg.discriminantField)},`);
  lines.push(`            variants: new Dictionary<string, Type>`);
  lines.push('            {');
  lines.push(entries);
  lines.push('            },');
  lines.push(`            allowUnknown: ${cfg.unknown ? 'true' : 'false'})`);
  lines.push('    {');
  lines.push('    }');
  lines.push('}');
  return lines.join('\n');
}

// ─── State File Generator ────────────────────────────────────────────────────

const STATE_ENUMS = [
  'PolicyState', 'PendingMessageKind', 'SessionLifecycle', 'SessionStatus',
  'SessionInputAnswerState', 'SessionInputAnswerValueKind', 'SessionInputQuestionKind',
  'SessionInputResponseKind',
  'TurnState', 'MessageAttachmentKind', 'ResponsePartKind', 'ToolCallStatus',
  'ToolCallConfirmationReason', 'ToolCallCancellationReason',
  'ConfirmationOptionKind',
  'ToolResultContentType', 'CustomizationType', 'CustomizationLoadStatus', 'TerminalClaimKind',
  'ChangesetStatus', 'ChangesetOperationStatus', 'ChangesetOperationScope', 'ResourceChangeType',
];

const STATE_STRUCTS: { name: string; omitDiscriminants?: boolean; csName?: string }[] = [
  { name: 'Icon' },
  { name: 'ProtectedResourceMetadata' },
  { name: 'RootState' },
  { name: 'RootConfigState' },
  { name: 'AgentInfo' },
  { name: 'SessionModelInfo' },
  { name: 'ModelSelection' },
  { name: 'AgentSelection' },
  { name: 'ConfigPropertySchema' },
  { name: 'ConfigSchema' },
  { name: 'PendingMessage' },
  { name: 'SessionState' },
  { name: 'SessionActiveClient' },
  { name: 'SessionSummary' },
  { name: 'ProjectInfo' },
  { name: 'SessionConfigPropertySchema' },
  { name: 'SessionConfigSchema' },
  { name: 'SessionConfigState' },
  { name: 'Turn' },
  { name: 'ActiveTurn' },
  { name: 'Message' },
  { name: 'SessionInputOption' },
  { name: 'SessionInputTextAnswerValue' },
  { name: 'SessionInputNumberAnswerValue' },
  { name: 'SessionInputBooleanAnswerValue' },
  { name: 'SessionInputSelectedAnswerValue' },
  { name: 'SessionInputSelectedManyAnswerValue' },
  { name: 'SessionInputAnswered' },
  { name: 'SessionInputSkipped' },
  { name: 'SessionInputTextQuestion' },
  { name: 'SessionInputNumberQuestion' },
  { name: 'SessionInputBooleanQuestion' },
  { name: 'SessionInputSingleSelectQuestion' },
  { name: 'SessionInputMultiSelectQuestion' },
  { name: 'SessionInputRequest' },
  { name: 'TextPosition' },
  { name: 'TextRange' },
  { name: 'TextSelection' },
  { name: 'SimpleMessageAttachment' },
  { name: 'MessageEmbeddedResourceAttachment' },
  { name: 'MessageResourceAttachment' },
  { name: 'MarkdownResponsePart' },
  { name: 'ContentRef' },
  { name: 'ResourceReponsePart', csName: 'ResourceResponsePart' },
  { name: 'ToolCallResponsePart' },
  { name: 'ReasoningResponsePart' },
  { name: 'SystemNotificationResponsePart' },
  { name: 'ToolCallResult' },
  { name: 'ConfirmationOption' },
  { name: 'ToolCallStreamingState' },
  { name: 'ToolCallPendingConfirmationState' },
  { name: 'ToolCallRunningState' },
  { name: 'ToolCallPendingResultConfirmationState' },
  { name: 'ToolCallCompletedState' },
  { name: 'ToolCallCancelledState' },
  { name: 'ToolDefinition' },
  { name: 'ToolAnnotations' },
  { name: 'ToolResultTextContent' },
  { name: 'ToolResultEmbeddedResourceContent' },
  { name: 'ToolResultResourceContent' },
  { name: 'ToolResultFileEditContent' },
  { name: 'ToolResultTerminalContent' },
  { name: 'ToolResultSubagentContent' },
  { name: 'CustomizationLoadingState' },
  { name: 'CustomizationLoadedState' },
  { name: 'CustomizationDegradedState' },
  { name: 'CustomizationErrorState' },
  { name: 'PluginCustomization' },
  { name: 'ClientPluginCustomization' },
  { name: 'DirectoryCustomization' },
  { name: 'AgentCustomization' },
  { name: 'SkillCustomization' },
  { name: 'PromptCustomization' },
  { name: 'RuleCustomization' },
  { name: 'HookCustomization' },
  { name: 'McpServerCustomization' },
  { name: 'FileEdit' },
  { name: 'TerminalInfo' },
  { name: 'TerminalClientClaim' },
  { name: 'TerminalSessionClaim' },
  { name: 'TerminalState' },
  { name: 'TerminalUnclassifiedPart' },
  { name: 'TerminalCommandPart' },
  { name: 'UsageInfo' },
  { name: 'ErrorInfo' },
  { name: 'Snapshot' },
  { name: 'ChangesetSummary' },
  { name: 'ChangesetState' },
  { name: 'ChangesetFile' },
  { name: 'ChangesetOperation' },
  { name: 'TelemetryCapabilities' },
  { name: 'ResourceWatchState' },
  { name: 'ResourceChange' },
];

const RESPONSE_PART_UNION: UnionConfig = {
  name: 'ResponsePart',
  discriminantField: 'kind',
  doc: 'ResponsePart is a single part of a response stream (text, tool call, reasoning, content reference).',
  variants: [
    { variantName: 'Markdown', innerType: 'MarkdownResponsePart', wireValue: 'markdown' },
    { variantName: 'ContentRef', innerType: 'ResourceResponsePart', wireValue: 'contentRef' },
    { variantName: 'ToolCall', innerType: 'ToolCallResponsePart', wireValue: 'toolCall' },
    { variantName: 'Reasoning', innerType: 'ReasoningResponsePart', wireValue: 'reasoning' },
    { variantName: 'SystemNotification', innerType: 'SystemNotificationResponsePart', wireValue: 'systemNotification' },
  ],
  unknown: true,
};

const TOOL_CALL_STATE_UNION: UnionConfig = {
  name: 'ToolCallState',
  discriminantField: 'status',
  doc: 'ToolCallState is the full tool call lifecycle state.',
  variants: [
    { variantName: 'Streaming', innerType: 'ToolCallStreamingState', wireValue: 'streaming' },
    { variantName: 'PendingConfirmation', innerType: 'ToolCallPendingConfirmationState', wireValue: 'pending-confirmation' },
    { variantName: 'Running', innerType: 'ToolCallRunningState', wireValue: 'running' },
    { variantName: 'PendingResultConfirmation', innerType: 'ToolCallPendingResultConfirmationState', wireValue: 'pending-result-confirmation' },
    { variantName: 'Completed', innerType: 'ToolCallCompletedState', wireValue: 'completed' },
    { variantName: 'Cancelled', innerType: 'ToolCallCancelledState', wireValue: 'cancelled' },
  ],
  unknown: true,
};

const TERMINAL_CLAIM_UNION: UnionConfig = {
  name: 'TerminalClaim',
  discriminantField: 'kind',
  doc: 'TerminalClaim identifies who currently holds a terminal.',
  variants: [
    { variantName: 'Client', innerType: 'TerminalClientClaim', wireValue: 'client' },
    { variantName: 'Session', innerType: 'TerminalSessionClaim', wireValue: 'session' },
  ],
  unknown: true,
};

const TERMINAL_CONTENT_PART_UNION: UnionConfig = {
  name: 'TerminalContentPart',
  discriminantField: 'type',
  doc: 'TerminalContentPart is a content part within terminal output.',
  variants: [
    { variantName: 'Unclassified', innerType: 'TerminalUnclassifiedPart', wireValue: 'unclassified' },
    { variantName: 'Command', innerType: 'TerminalCommandPart', wireValue: 'command' },
  ],
  unknown: true,
};

const SESSION_INPUT_QUESTION_UNION: UnionConfig = {
  name: 'SessionInputQuestion',
  discriminantField: 'kind',
  doc: 'SessionInputQuestion is one question within a session input request.',
  variants: [
    { variantName: 'Text', innerType: 'SessionInputTextQuestion', wireValue: 'text' },
    { variantName: 'Number', innerType: 'SessionInputNumberQuestion', wireValue: 'number' },
    { variantName: 'Integer', innerType: 'SessionInputNumberQuestion', wireValue: 'integer' },
    { variantName: 'Boolean', innerType: 'SessionInputBooleanQuestion', wireValue: 'boolean' },
    { variantName: 'SingleSelect', innerType: 'SessionInputSingleSelectQuestion', wireValue: 'single-select' },
    { variantName: 'MultiSelect', innerType: 'SessionInputMultiSelectQuestion', wireValue: 'multi-select' },
  ],
  unknown: true,
};

const SESSION_INPUT_ANSWER_VALUE_UNION: UnionConfig = {
  name: 'SessionInputAnswerValue',
  discriminantField: 'kind',
  doc: 'SessionInputAnswerValue is the value captured for one answer.',
  variants: [
    { variantName: 'Text', innerType: 'SessionInputTextAnswerValue', wireValue: 'text' },
    { variantName: 'Number', innerType: 'SessionInputNumberAnswerValue', wireValue: 'number' },
    { variantName: 'Boolean', innerType: 'SessionInputBooleanAnswerValue', wireValue: 'boolean' },
    { variantName: 'Selected', innerType: 'SessionInputSelectedAnswerValue', wireValue: 'selected' },
    { variantName: 'SelectedMany', innerType: 'SessionInputSelectedManyAnswerValue', wireValue: 'selected-many' },
  ],
  unknown: true,
};

const SESSION_INPUT_ANSWER_UNION: UnionConfig = {
  name: 'SessionInputAnswer',
  discriminantField: 'state',
  doc: 'SessionInputAnswer is a draft, submitted, or skipped answer for one question.',
  variants: [
    { variantName: 'Draft', innerType: 'SessionInputAnswered', wireValue: 'draft' },
    { variantName: 'Submitted', innerType: 'SessionInputAnswered', wireValue: 'submitted' },
    { variantName: 'Skipped', innerType: 'SessionInputSkipped', wireValue: 'skipped' },
  ],
  unknown: true,
};

const TOOL_RESULT_CONTENT_UNION: UnionConfig = {
  name: 'ToolResultContent',
  discriminantField: 'type',
  doc: 'ToolResultContent is a content block in a tool result.',
  variants: [
    { variantName: 'Text', innerType: 'ToolResultTextContent', wireValue: 'text' },
    { variantName: 'EmbeddedResource', innerType: 'ToolResultEmbeddedResourceContent', wireValue: 'embeddedResource' },
    { variantName: 'Resource', innerType: 'ToolResultResourceContent', wireValue: 'resource' },
    { variantName: 'FileEdit', innerType: 'ToolResultFileEditContent', wireValue: 'fileEdit' },
    { variantName: 'Terminal', innerType: 'ToolResultTerminalContent', wireValue: 'terminal' },
    { variantName: 'Subagent', innerType: 'ToolResultSubagentContent', wireValue: 'subagent' },
  ],
  unknown: true,
};

const MESSAGE_ATTACHMENT_UNION: UnionConfig = {
  name: 'MessageAttachment',
  discriminantField: 'type',
  doc: 'MessageAttachment is an attachment associated with a Message.',
  variants: [
    { variantName: 'Simple', innerType: 'SimpleMessageAttachment', wireValue: 'simple' },
    { variantName: 'EmbeddedResource', innerType: 'MessageEmbeddedResourceAttachment', wireValue: 'embeddedResource' },
    { variantName: 'Resource', innerType: 'MessageResourceAttachment', wireValue: 'resource' },
  ],
  unknown: true,
};

const CUSTOMIZATION_UNION: UnionConfig = {
  name: 'Customization',
  discriminantField: 'type',
  doc: 'Customization is a top-level customization (plugin or directory).',
  variants: [
    { variantName: 'Plugin', innerType: 'PluginCustomization', wireValue: 'plugin' },
    { variantName: 'Directory', innerType: 'DirectoryCustomization', wireValue: 'directory' },
  ],
  unknown: true,
};

const CHILD_CUSTOMIZATION_UNION: UnionConfig = {
  name: 'ChildCustomization',
  discriminantField: 'type',
  doc: 'ChildCustomization is a child customization living inside a plugin or directory.',
  variants: [
    { variantName: 'Agent', innerType: 'AgentCustomization', wireValue: 'agent' },
    { variantName: 'Skill', innerType: 'SkillCustomization', wireValue: 'skill' },
    { variantName: 'Prompt', innerType: 'PromptCustomization', wireValue: 'prompt' },
    { variantName: 'Rule', innerType: 'RuleCustomization', wireValue: 'rule' },
    { variantName: 'Hook', innerType: 'HookCustomization', wireValue: 'hook' },
    { variantName: 'McpServer', innerType: 'McpServerCustomization', wireValue: 'mcpServer' },
  ],
  unknown: true,
};

const CUSTOMIZATION_LOAD_STATE_UNION: UnionConfig = {
  name: 'CustomizationLoadState',
  discriminantField: 'kind',
  doc: 'CustomizationLoadState is the host-reported load state for a container customization.',
  variants: [
    { variantName: 'Loading', innerType: 'CustomizationLoadingState', wireValue: 'loading' },
    { variantName: 'Loaded', innerType: 'CustomizationLoadedState', wireValue: 'loaded' },
    { variantName: 'Degraded', innerType: 'CustomizationDegradedState', wireValue: 'degraded' },
    { variantName: 'Error', innerType: 'CustomizationErrorState', wireValue: 'error' },
  ],
  unknown: true,
};

function generateSnapshotState(): string {
  return `/// <summary>
/// SnapshotState is the state payload of a snapshot — root, session,
/// terminal, or changeset state. UnmarshalJSON probes for required fields
/// in the canonical order (session → terminal → changeset → root).
/// </summary>
[JsonConverter(typeof(SnapshotStateConverter))]
public sealed class SnapshotState
{
    /// <summary>Root state variant, when populated.</summary>
    public RootState? Root { get; set; }

    /// <summary>Session state variant, when populated.</summary>
    public SessionState? Session { get; set; }

    /// <summary>Terminal state variant, when populated.</summary>
    public TerminalState? Terminal { get; set; }

    /// <summary>Changeset state variant, when populated.</summary>
    public ChangesetState? Changeset { get; set; }
}

/// <summary>System.Text.Json converter for the SnapshotState shape-probed union.</summary>
internal sealed class SnapshotStateConverter : JsonConverter<SnapshotState>
{
    public override SnapshotState Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
    {
        using var doc = JsonDocument.ParseValue(ref reader);
        var root = doc.RootElement;
        var result = new SnapshotState();
        if (root.TryGetProperty("summary", out _) && root.TryGetProperty("lifecycle", out _))
        {
            result.Session = root.Deserialize<SessionState>(options);
        }
        else if (root.TryGetProperty("content", out _))
        {
            result.Terminal = root.Deserialize<TerminalState>(options);
        }
        else if (root.TryGetProperty("status", out _) && root.TryGetProperty("files", out _))
        {
            result.Changeset = root.Deserialize<ChangesetState>(options);
        }
        else
        {
            result.Root = root.Deserialize<RootState>(options);
        }
        return result;
    }

    public override void Write(Utf8JsonWriter writer, SnapshotState value, JsonSerializerOptions options)
    {
        if (value.Session is not null) { JsonSerializer.Serialize(writer, value.Session, options); return; }
        if (value.Terminal is not null) { JsonSerializer.Serialize(writer, value.Terminal, options); return; }
        if (value.Changeset is not null) { JsonSerializer.Serialize(writer, value.Changeset, options); return; }
        if (value.Root is not null) { JsonSerializer.Serialize(writer, value.Root, options); return; }
        writer.WriteNullValue();
    }
}`;
}

function generateStateFile(project: Project): string {
  const lines: string[] = [fileHeader()];

  lines.push('// ─── Enums ────────────────────────────────────────────────────────────\n');
  for (const enumName of STATE_ENUMS) {
    const decl = findEnum(project, enumName);
    if (decl) {
      lines.push(generateEnum(decl));
      lines.push('');
    }
  }

  lines.push('// ─── Classes ──────────────────────────────────────────────────────────\n');
  for (const entry of STATE_STRUCTS) {
    try {
      lines.push(
        generateClassFromInterface(project, entry.name, entry.csName, {
          omitDiscriminants: entry.omitDiscriminants,
        }),
      );
      lines.push('');
    } catch (e) {
      lines.push(`// TODO: could not generate ${entry.name}: ${e}`);
      lines.push('');
    }
  }

  lines.push('// ─── Discriminated Unions ─────────────────────────────────────────────\n');
  for (const u of [
    RESPONSE_PART_UNION, TOOL_CALL_STATE_UNION, TERMINAL_CLAIM_UNION,
    TERMINAL_CONTENT_PART_UNION, SESSION_INPUT_QUESTION_UNION,
    SESSION_INPUT_ANSWER_VALUE_UNION, SESSION_INPUT_ANSWER_UNION,
    TOOL_RESULT_CONTENT_UNION, MESSAGE_ATTACHMENT_UNION, CUSTOMIZATION_UNION,
    CHILD_CUSTOMIZATION_UNION, CUSTOMIZATION_LOAD_STATE_UNION,
  ]) {
    lines.push(generateDiscriminatedUnion(u));
    lines.push('');
  }
  lines.push(generateSnapshotState());
  lines.push('');

  return lines.join('\n');
}

// ─── Actions File Generator ──────────────────────────────────────────────────

const ACTION_VARIANTS: { type: string; variantName: string; tsInterface: string }[] = [
  { type: 'root/agentsChanged', variantName: 'RootAgentsChanged', tsInterface: 'RootAgentsChangedAction' },
  { type: 'root/activeSessionsChanged', variantName: 'RootActiveSessionsChanged', tsInterface: 'RootActiveSessionsChangedAction' },
  { type: 'root/configChanged', variantName: 'RootConfigChanged', tsInterface: 'RootConfigChangedAction' },
  { type: 'session/ready', variantName: 'SessionReady', tsInterface: 'SessionReadyAction' },
  { type: 'session/creationFailed', variantName: 'SessionCreationFailed', tsInterface: 'SessionCreationFailedAction' },
  { type: 'session/turnStarted', variantName: 'SessionTurnStarted', tsInterface: 'SessionTurnStartedAction' },
  { type: 'session/delta', variantName: 'SessionDelta', tsInterface: 'SessionDeltaAction' },
  { type: 'session/responsePart', variantName: 'SessionResponsePart', tsInterface: 'SessionResponsePartAction' },
  { type: 'session/toolCallStart', variantName: 'SessionToolCallStart', tsInterface: 'SessionToolCallStartAction' },
  { type: 'session/toolCallDelta', variantName: 'SessionToolCallDelta', tsInterface: 'SessionToolCallDeltaAction' },
  { type: 'session/toolCallReady', variantName: 'SessionToolCallReady', tsInterface: 'SessionToolCallReadyAction' },
  { type: 'session/toolCallConfirmed', variantName: 'SessionToolCallConfirmed', tsInterface: '_merged_' },
  { type: 'session/toolCallComplete', variantName: 'SessionToolCallComplete', tsInterface: 'SessionToolCallCompleteAction' },
  { type: 'session/toolCallResultConfirmed', variantName: 'SessionToolCallResultConfirmed', tsInterface: 'SessionToolCallResultConfirmedAction' },
  { type: 'session/turnComplete', variantName: 'SessionTurnComplete', tsInterface: 'SessionTurnCompleteAction' },
  { type: 'session/turnCancelled', variantName: 'SessionTurnCancelled', tsInterface: 'SessionTurnCancelledAction' },
  { type: 'session/error', variantName: 'SessionError', tsInterface: 'SessionErrorAction' },
  { type: 'session/titleChanged', variantName: 'SessionTitleChanged', tsInterface: 'SessionTitleChangedAction' },
  { type: 'session/usage', variantName: 'SessionUsage', tsInterface: 'SessionUsageAction' },
  { type: 'session/reasoning', variantName: 'SessionReasoning', tsInterface: 'SessionReasoningAction' },
  { type: 'session/modelChanged', variantName: 'SessionModelChanged', tsInterface: 'SessionModelChangedAction' },
  { type: 'session/agentChanged', variantName: 'SessionAgentChanged', tsInterface: 'SessionAgentChangedAction' },
  { type: 'session/isReadChanged', variantName: 'SessionIsReadChanged', tsInterface: 'SessionIsReadChangedAction' },
  { type: 'session/isArchivedChanged', variantName: 'SessionIsArchivedChanged', tsInterface: 'SessionIsArchivedChangedAction' },
  { type: 'session/activityChanged', variantName: 'SessionActivityChanged', tsInterface: 'SessionActivityChangedAction' },
  { type: 'session/changesetsChanged', variantName: 'SessionChangesetsChanged', tsInterface: 'SessionChangesetsChangedAction' },
  { type: 'session/serverToolsChanged', variantName: 'SessionServerToolsChanged', tsInterface: 'SessionServerToolsChangedAction' },
  { type: 'session/activeClientChanged', variantName: 'SessionActiveClientChanged', tsInterface: 'SessionActiveClientChangedAction' },
  { type: 'session/activeClientToolsChanged', variantName: 'SessionActiveClientToolsChanged', tsInterface: 'SessionActiveClientToolsChangedAction' },
  { type: 'session/pendingMessageSet', variantName: 'SessionPendingMessageSet', tsInterface: 'SessionPendingMessageSetAction' },
  { type: 'session/pendingMessageRemoved', variantName: 'SessionPendingMessageRemoved', tsInterface: 'SessionPendingMessageRemovedAction' },
  { type: 'session/queuedMessagesReordered', variantName: 'SessionQueuedMessagesReordered', tsInterface: 'SessionQueuedMessagesReorderedAction' },
  { type: 'session/inputRequested', variantName: 'SessionInputRequested', tsInterface: 'SessionInputRequestedAction' },
  { type: 'session/inputAnswerChanged', variantName: 'SessionInputAnswerChanged', tsInterface: 'SessionInputAnswerChangedAction' },
  { type: 'session/inputCompleted', variantName: 'SessionInputCompleted', tsInterface: 'SessionInputCompletedAction' },
  { type: 'session/customizationsChanged', variantName: 'SessionCustomizationsChanged', tsInterface: 'SessionCustomizationsChangedAction' },
  { type: 'session/customizationToggled', variantName: 'SessionCustomizationToggled', tsInterface: 'SessionCustomizationToggledAction' },
  { type: 'session/customizationUpdated', variantName: 'SessionCustomizationUpdated', tsInterface: 'SessionCustomizationUpdatedAction' },
  { type: 'session/customizationRemoved', variantName: 'SessionCustomizationRemoved', tsInterface: 'SessionCustomizationRemovedAction' },
  { type: 'session/truncated', variantName: 'SessionTruncated', tsInterface: 'SessionTruncatedAction' },
  { type: 'session/configChanged', variantName: 'SessionConfigChanged', tsInterface: 'SessionConfigChangedAction' },
  { type: 'session/metaChanged', variantName: 'SessionMetaChanged', tsInterface: 'SessionMetaChangedAction' },
  { type: 'session/toolCallContentChanged', variantName: 'SessionToolCallContentChanged', tsInterface: 'SessionToolCallContentChangedAction' },
  { type: 'changeset/statusChanged', variantName: 'ChangesetStatusChanged', tsInterface: 'ChangesetStatusChangedAction' },
  { type: 'changeset/fileSet', variantName: 'ChangesetFileSet', tsInterface: 'ChangesetFileSetAction' },
  { type: 'changeset/fileRemoved', variantName: 'ChangesetFileRemoved', tsInterface: 'ChangesetFileRemovedAction' },
  { type: 'changeset/operationsChanged', variantName: 'ChangesetOperationsChanged', tsInterface: 'ChangesetOperationsChangedAction' },
  { type: 'changeset/operationStatusChanged', variantName: 'ChangesetOperationStatusChanged', tsInterface: 'ChangesetOperationStatusChangedAction' },
  { type: 'changeset/cleared', variantName: 'ChangesetCleared', tsInterface: 'ChangesetClearedAction' },
  { type: 'root/terminalsChanged', variantName: 'RootTerminalsChanged', tsInterface: 'RootTerminalsChangedAction' },
  { type: 'terminal/data', variantName: 'TerminalData', tsInterface: 'TerminalDataAction' },
  { type: 'terminal/input', variantName: 'TerminalInput', tsInterface: 'TerminalInputAction' },
  { type: 'terminal/resized', variantName: 'TerminalResized', tsInterface: 'TerminalResizedAction' },
  { type: 'terminal/claimed', variantName: 'TerminalClaimed', tsInterface: 'TerminalClaimedAction' },
  { type: 'terminal/titleChanged', variantName: 'TerminalTitleChanged', tsInterface: 'TerminalTitleChangedAction' },
  { type: 'terminal/cwdChanged', variantName: 'TerminalCwdChanged', tsInterface: 'TerminalCwdChangedAction' },
  { type: 'terminal/exited', variantName: 'TerminalExited', tsInterface: 'TerminalExitedAction' },
  { type: 'terminal/cleared', variantName: 'TerminalCleared', tsInterface: 'TerminalClearedAction' },
  { type: 'terminal/commandDetectionAvailable', variantName: 'TerminalCommandDetectionAvailable', tsInterface: 'TerminalCommandDetectionAvailableAction' },
  { type: 'terminal/commandExecuted', variantName: 'TerminalCommandExecuted', tsInterface: 'TerminalCommandExecutedAction' },
  { type: 'terminal/commandFinished', variantName: 'TerminalCommandFinished', tsInterface: 'TerminalCommandFinishedAction' },
  { type: 'resourceWatch/changed', variantName: 'ResourceWatchChanged', tsInterface: 'ResourceWatchChangedAction' },
];

function generateMergedToolCallConfirmedClass(): string {
  return `/// <summary>
/// SessionToolCallConfirmedAction — the client approves or denies a
/// pending tool call (merged approved + denied variants on the wire).
/// </summary>
public sealed class SessionToolCallConfirmedAction
{
    [JsonPropertyName("type")]
    public ActionType Type { get; set; }

    [JsonPropertyName("turnId")]
    public string TurnId { get; set; } = "";

    [JsonPropertyName("toolCallId")]
    public string ToolCallId { get; set; } = "";

    [JsonPropertyName("_meta")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public Dictionary<string, JsonElement>? Meta { get; set; }

    [JsonPropertyName("approved")]
    public bool Approved { get; set; }

    [JsonPropertyName("confirmed")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public ToolCallConfirmationReason? Confirmed { get; set; }

    [JsonPropertyName("reason")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public ToolCallCancellationReason? Reason { get; set; }

    [JsonPropertyName("editedToolInput")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? EditedToolInput { get; set; }

    [JsonPropertyName("userSuggestion")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public Message? UserSuggestion { get; set; }

    [JsonPropertyName("reasonMessage")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public StringOrMarkdown? ReasonMessage { get; set; }

    [JsonPropertyName("selectedOptionId")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? SelectedOptionId { get; set; }
}`;
}

function generateActionEnvelope(): string {
  return `/// <summary>
/// ActionEnvelope wraps every action with the channel URI it belongs to,
/// the server-assigned monotonic sequence number, and an optional origin.
/// </summary>
public sealed class ActionEnvelope
{
    [JsonPropertyName("channel")]
    public string Channel { get; set; } = "";

    [JsonPropertyName("action")]
    public StateAction Action { get; set; } = new();

    [JsonPropertyName("serverSeq")]
    public long ServerSeq { get; set; }

    [JsonPropertyName("origin")]
    public ActionOrigin? Origin { get; set; }

    [JsonPropertyName("rejectionReason")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? RejectionReason { get; set; }
}`;
}

function generateActionsUnion(): string {
  const cfg: UnionConfig = {
    name: 'StateAction',
    discriminantField: 'type',
    doc: 'StateAction is the discriminated union of every state action.',
    variants: ACTION_VARIANTS.map((v) => ({
      variantName: v.variantName,
      innerType: v.tsInterface === '_merged_' ? 'SessionToolCallConfirmedAction' : stripIPrefix(v.tsInterface),
      wireValue: v.type,
    })),
    unknown: true,
  };
  return generateDiscriminatedUnion(cfg);
}

function generateActionsFile(project: Project): string {
  const lines: string[] = [fileHeader()];

  lines.push('// ─── ActionType ──────────────────────────────────────────────────────\n');
  const actionTypeEnum = findEnum(project, 'ActionType');
  lines.push(actionTypeEnum ? generateEnum(actionTypeEnum) : '// TODO: ActionType enum not found');
  lines.push('');

  lines.push('// ─── Action Envelope ─────────────────────────────────────────────────\n');
  lines.push(generateClassFromInterface(project, 'ActionOrigin'));
  lines.push('');
  lines.push(generateActionEnvelope());
  lines.push('');

  lines.push('// ─── Action Payloads ─────────────────────────────────────────────────\n');
  for (const v of ACTION_VARIANTS) {
    if (v.tsInterface === '_merged_') {
      lines.push(generateMergedToolCallConfirmedClass());
      lines.push('');
      continue;
    }
    try {
      lines.push(generateClassFromInterface(project, v.tsInterface, undefined, { includeDiscriminants: true }));
      lines.push('');
    } catch (e) {
      lines.push(`// TODO: could not generate ${v.tsInterface}: ${e}`);
      lines.push('');
    }
  }

  lines.push('// ─── StateAction Union ───────────────────────────────────────────────\n');
  lines.push(generateActionsUnion());
  lines.push('');

  return lines.join('\n');
}

// ─── Commands File Generator ─────────────────────────────────────────────────

const COMMAND_ENUMS = ['ReconnectResultType', 'ContentEncoding', 'CompletionItemKind', 'ResourceType', 'ResourceWriteMode'];

const COMMAND_STRUCTS: { name: string; omitDiscriminants?: boolean; csName?: string }[] = [
  { name: 'InitializeParams' }, { name: 'InitializeResult' },
  { name: 'ReconnectParams' },
  // Union variants MUST self-carry their `type` discriminator: UnionConverter<T>.Write
  // serializes the inner value by its runtime type and relies on that property to
  // emit the discriminator (matching ACTION_VARIANTS' includeDiscriminants). Omitting
  // it silently drops `type` on write, breaking the reconnect-result round-trip.
  { name: 'ReconnectReplayResult' },
  { name: 'ReconnectSnapshotResult' },
  { name: 'SubscribeParams' }, { name: 'SubscribeResult' },
  { name: 'SessionForkSource' }, { name: 'CreateSessionParams' },
  { name: 'DisposeSessionParams' },
  { name: 'ListSessionsParams' }, { name: 'ListSessionsResult' },
  { name: 'ResourceReadParams' }, { name: 'ResourceReadResult' },
  { name: 'ResourceWriteParams' }, { name: 'ResourceWriteResult' },
  { name: 'ResourceListParams' }, { name: 'ResourceListResult' },
  { name: 'DirectoryEntry' },
  { name: 'ResourceCopyParams' }, { name: 'ResourceCopyResult' },
  { name: 'ResourceDeleteParams' }, { name: 'ResourceDeleteResult' },
  { name: 'ResourceMoveParams' }, { name: 'ResourceMoveResult' },
  { name: 'ResourceResolveParams' }, { name: 'ResourceResolveResult' },
  { name: 'ResourceMkdirParams' }, { name: 'ResourceMkdirResult' },
  { name: 'ResourceRequestParams' }, { name: 'ResourceRequestResult' },
  { name: 'CreateResourceWatchParams' }, { name: 'CreateResourceWatchResult' },
  { name: 'FetchTurnsParams' }, { name: 'FetchTurnsResult' },
  { name: 'UnsubscribeParams' }, { name: 'DispatchActionParams' },
  { name: 'AuthenticateParams' }, { name: 'AuthenticateResult' },
  { name: 'CreateTerminalParams' }, { name: 'DisposeTerminalParams' },
  { name: 'ResolveSessionConfigParams' }, { name: 'ResolveSessionConfigResult' },
  { name: 'SessionConfigCompletionsParams' }, { name: 'SessionConfigCompletionsResult' },
  { name: 'SessionConfigValueItem' },
  { name: 'CompletionsParams' }, { name: 'CompletionItem' }, { name: 'CompletionsResult' },
  { name: 'InvokeChangesetOperationParams' }, { name: 'InvokeChangesetOperationResult' },
  { name: 'ChangesetOperationFollowUp' },
];

const RECONNECT_RESULT_UNION: UnionConfig = {
  name: 'ReconnectResult',
  discriminantField: 'type',
  doc: 'ReconnectResult is the result of the `reconnect` command.',
  variants: [
    { variantName: 'Replay', innerType: 'ReconnectReplayResult', wireValue: 'replay' },
    { variantName: 'Snapshot', innerType: 'ReconnectSnapshotResult', wireValue: 'snapshot' },
  ],
};

function generateChangesetOperationTargetCs(): string {
  return `/// <summary>
/// ChangesetOperationTarget identifies the file or range a
/// ChangesetOperation should act on.
/// </summary>
[JsonConverter(typeof(ChangesetOperationTargetConverter))]
public sealed class ChangesetOperationTarget : AhpUnion
{
    public ChangesetOperationTarget() { }
    public ChangesetOperationTarget(object? value) : base(value) { }
}

/// <summary>Targets an entire resource.</summary>
public sealed class ChangesetOperationResourceTarget
{
    [JsonPropertyName("kind")]
    public string Kind { get; set; } = "resource";

    [JsonPropertyName("resource")]
    public string Resource { get; set; } = "";

    [JsonPropertyName("side")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? Side { get; set; }
}

/// <summary>Targets a range within a resource.</summary>
public sealed class ChangesetOperationRangeTarget
{
    [JsonPropertyName("kind")]
    public string Kind { get; set; } = "range";

    [JsonPropertyName("resource")]
    public string Resource { get; set; } = "";

    [JsonPropertyName("side")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? Side { get; set; }

    [JsonPropertyName("range")]
    public ChangesetOperationTargetRange Range { get; set; } = new();
}

/// <summary>The [start, end] index pair for a range target.</summary>
public sealed class ChangesetOperationTargetRange
{
    [JsonPropertyName("start")]
    public long Start { get; set; }

    [JsonPropertyName("end")]
    public long End { get; set; }
}

/// <summary>System.Text.Json converter for the ChangesetOperationTarget union.</summary>
internal sealed class ChangesetOperationTargetConverter : UnionConverter<ChangesetOperationTarget>
{
    public ChangesetOperationTargetConverter()
        : base(
            discriminator: "kind",
            variants: new Dictionary<string, Type>
            {
                ["resource"] = typeof(ChangesetOperationResourceTarget),
                ["range"] = typeof(ChangesetOperationRangeTarget),
            },
            allowUnknown: false)
    {
    }
}`;
}

function generateCommandsFile(project: Project): string {
  const lines: string[] = [fileHeader()];

  lines.push('// ─── Enums ────────────────────────────────────────────────────────────\n');
  for (const enumName of COMMAND_ENUMS) {
    const decl = findEnum(project, enumName);
    if (decl) {
      lines.push(generateEnum(decl));
      lines.push('');
    }
  }

  lines.push('// ─── Command Payloads ─────────────────────────────────────────────────\n');
  const generated = new Set<string>();
  for (const entry of COMMAND_STRUCTS) {
    if (generated.has(entry.name)) continue;
    generated.add(entry.name);
    try {
      lines.push(
        generateClassFromInterface(project, entry.name, entry.csName, {
          omitDiscriminants: entry.omitDiscriminants,
        }),
      );
      lines.push('');
    } catch (e) {
      lines.push(`// TODO: could not generate ${entry.name}: ${e}`);
      lines.push('');
    }
  }

  lines.push('// ─── ReconnectResult Union ────────────────────────────────────────────\n');
  lines.push(generateDiscriminatedUnion(RECONNECT_RESULT_UNION));
  lines.push('');

  lines.push('// ─── Changeset Operation Unions ───────────────────────────────────────\n');
  lines.push(generateChangesetOperationTargetCs());
  lines.push('');

  return lines.join('\n');
}

// ─── Notifications File Generator ────────────────────────────────────────────

const NOTIFICATION_ENUMS = ['AuthRequiredReason'];

const NOTIFICATION_STRUCTS = [
  'SessionAddedParams',
  'SessionRemovedParams',
  'SessionSummaryChangedParams',
  'AuthRequiredParams',
  'OtlpExportLogsParams',
  'OtlpExportTracesParams',
  'OtlpExportMetricsParams',
];

function generateNotificationsFile(project: Project): string {
  const lines: string[] = [fileHeader()];

  lines.push('// ─── Enums ────────────────────────────────────────────────────────────\n');
  for (const enumName of NOTIFICATION_ENUMS) {
    const decl = findEnum(project, enumName);
    if (decl) {
      lines.push(generateEnum(decl));
      lines.push('');
    }
  }

  const priorPartials = new Set(requiredPartialStructs);

  lines.push('// ─── Notification Payloads ────────────────────────────────────────────\n');
  for (const tsName of NOTIFICATION_STRUCTS) {
    try {
      lines.push(generateClassFromInterface(project, tsName, undefined, { omitDiscriminants: true }));
      lines.push('');
    } catch (e) {
      lines.push(`// TODO: could not generate ${tsName}: ${e}`);
      lines.push('');
    }
  }

  const newPartials = [...requiredPartialStructs].filter((n) => !priorPartials.has(n));
  if (newPartials.length > 0) {
    lines.push('// ─── Partial Summaries ────────────────────────────────────────────────\n');
    for (const tsName of newPartials) {
      try {
        lines.push(generatePartialClass(project, tsName));
        lines.push('');
      } catch (e) {
        lines.push(`// TODO: could not generate Partial<${tsName}>: ${e}`);
        lines.push('');
      }
    }
  }

  return lines.join('\n');
}

// ─── Errors File Generator ───────────────────────────────────────────────────

function generateErrorsFile(): string {
  return `${fileHeader()}
/// <summary>Standard JSON-RPC 2.0 error codes.</summary>
public static class JsonRpcErrorCodes
{
    /// <summary>The request body was invalid JSON.</summary>
    public const int ParseError = -32700;

    /// <summary>The payload was not a valid JSON-RPC request.</summary>
    public const int InvalidRequest = -32600;

    /// <summary>The requested method does not exist on the server.</summary>
    public const int MethodNotFound = -32601;

    /// <summary>The method parameters did not match the declared schema.</summary>
    public const int InvalidParams = -32602;

    /// <summary>An unspecified server failure.</summary>
    public const int InternalError = -32603;
}

/// <summary>AHP application-specific error codes (above the JSON-RPC reserved range).</summary>
public static class AhpErrorCodes
{
    public const int SessionNotFound = -32001;
    public const int ProviderNotFound = -32002;
    public const int SessionAlreadyExists = -32003;
    public const int TurnInProgress = -32004;
    public const int UnsupportedProtocolVersion = -32005;
    public const int ContentNotFound = -32006;
    public const int AuthRequired = -32007;
    public const int NotFound = -32008;
    public const int PermissionDenied = -32009;
    public const int AlreadyExists = -32010;
}

/// <summary>Detail payload of an AuthRequired (-32007) error.</summary>
public sealed class AuthRequiredErrorData
{
    [JsonPropertyName("resources")]
    public List<ProtectedResourceMetadata> Resources { get; set; } = new();
}

/// <summary>Detail payload of a PermissionDenied (-32009) error.</summary>
public sealed class PermissionDeniedErrorData
{
    [JsonPropertyName("request")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public ResourceRequestParams? Request { get; set; }
}

/// <summary>Detail payload of an UnsupportedProtocolVersion (-32005) error.</summary>
public sealed class UnsupportedProtocolVersionErrorData
{
    [JsonPropertyName("supportedVersions")]
    public List<string> SupportedVersions { get; set; } = new();
}
`;
}

// ─── Messages File Generator ─────────────────────────────────────────────────

function generateMessagesFile(): string {
  return `${fileHeader()}
/// <summary>The canonical JSON-RPC version literal (<c>"2.0"</c>).</summary>
public static class JsonRpc
{
    /// <summary>The sole allowed value of the <c>jsonrpc</c> field.</summary>
    public const string Version = "2.0";
}

/// <summary>A JSON-RPC 2.0 request (method + id).</summary>
public sealed class JsonRpcRequest
{
    [JsonPropertyName("jsonrpc")]
    public string JsonRpcVersion { get; set; } = JsonRpc.Version;

    [JsonPropertyName("id")]
    public ulong Id { get; set; }

    [JsonPropertyName("method")]
    public string Method { get; set; } = "";

    [JsonPropertyName("params")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public JsonElement? Params { get; set; }
}

/// <summary>A JSON-RPC 2.0 success response.</summary>
public sealed class JsonRpcSuccessResponse
{
    [JsonPropertyName("jsonrpc")]
    public string JsonRpcVersion { get; set; } = JsonRpc.Version;

    [JsonPropertyName("id")]
    public ulong Id { get; set; }

    [JsonPropertyName("result")]
    public JsonElement Result { get; set; }
}

/// <summary>A JSON-RPC 2.0 error response.</summary>
public sealed class JsonRpcErrorResponse
{
    [JsonPropertyName("jsonrpc")]
    public string JsonRpcVersion { get; set; } = JsonRpc.Version;

    [JsonPropertyName("id")]
    public ulong Id { get; set; }

    [JsonPropertyName("error")]
    public JsonRpcErrorObject Error { get; set; } = new();
}

/// <summary>The standard JSON-RPC 2.0 error object.</summary>
public sealed class JsonRpcErrorObject
{
    [JsonPropertyName("code")]
    public int Code { get; set; }

    [JsonPropertyName("message")]
    public string Message { get; set; } = "";

    [JsonPropertyName("data")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public JsonElement? Data { get; set; }
}

/// <summary>A JSON-RPC 2.0 notification (method, no id).</summary>
public sealed class JsonRpcNotification
{
    [JsonPropertyName("jsonrpc")]
    public string JsonRpcVersion { get; set; } = JsonRpc.Version;

    [JsonPropertyName("method")]
    public string Method { get; set; } = "";

    [JsonPropertyName("params")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public JsonElement? Params { get; set; }
}

/// <summary>
/// A discriminated union over the four JSON-RPC message shapes. The active
/// variant is chosen by JSON-RPC 2.0's shape rules:
/// request (id + method), notification (method, no id),
/// success-response (id + result), error-response (id + error).
/// </summary>
[JsonConverter(typeof(JsonRpcMessageConverter))]
public sealed class JsonRpcMessage
{
    public JsonRpcRequest? Request { get; set; }
    public JsonRpcSuccessResponse? SuccessResponse { get; set; }
    public JsonRpcErrorResponse? ErrorResponse { get; set; }
    public JsonRpcNotification? Notification { get; set; }
}

/// <summary>System.Text.Json converter for the shape-probed JsonRpcMessage union.</summary>
internal sealed class JsonRpcMessageConverter : JsonConverter<JsonRpcMessage>
{
    public override JsonRpcMessage Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
    {
        using var doc = JsonDocument.ParseValue(ref reader);
        var root = doc.RootElement;
        bool hasMethod = root.TryGetProperty("method", out _);
        bool hasId = root.TryGetProperty("id", out _);
        bool hasResult = root.TryGetProperty("result", out _);
        bool hasError = root.TryGetProperty("error", out _);
        var msg = new JsonRpcMessage();
        if (hasMethod && hasId)
        {
            msg.Request = root.Deserialize<JsonRpcRequest>(options);
        }
        else if (hasMethod)
        {
            msg.Notification = root.Deserialize<JsonRpcNotification>(options);
        }
        else if (hasError)
        {
            msg.ErrorResponse = root.Deserialize<JsonRpcErrorResponse>(options);
        }
        else if (hasResult)
        {
            msg.SuccessResponse = root.Deserialize<JsonRpcSuccessResponse>(options);
        }
        else
        {
            throw new JsonException("JSON-RPC message has no method/result/error");
        }
        return msg;
    }

    public override void Write(Utf8JsonWriter writer, JsonRpcMessage value, JsonSerializerOptions options)
    {
        if (value.Request is not null) { JsonSerializer.Serialize(writer, value.Request, options); return; }
        if (value.SuccessResponse is not null) { JsonSerializer.Serialize(writer, value.SuccessResponse, options); return; }
        if (value.ErrorResponse is not null) { JsonSerializer.Serialize(writer, value.ErrorResponse, options); return; }
        if (value.Notification is not null) { JsonSerializer.Serialize(writer, value.Notification, options); return; }
        writer.WriteNullValue();
    }
}
`;
}

// ─── Version File Generator ──────────────────────────────────────────────────

function generateVersionFile(project: Project): string {
  const { current, supported } = readProtocolVersions(project);
  const supportedLiteral = supported.map((v) => `        ${JSON.stringify(v)},`).join('\n');
  return `${fileHeader()}
/// <summary>Protocol version constants for the Agent Host Protocol.</summary>
public static class ProtocolVersion
{
    /// <summary>
    /// The current protocol version (SemVer MAJOR.MINOR.PATCH) this
    /// generated source speaks.
    /// </summary>
    public const string Current = ${JSON.stringify(current)};

    private static readonly string[] s_supported =
    {
${supportedLiteral}
    };

    /// <summary>
    /// Every protocol version this client is willing to negotiate, ordered
    /// most-preferred-first. The first entry always equals <see cref="Current"/>.
    /// A fresh copy is returned on every call so callers may mutate it freely.
    /// </summary>
    public static IReadOnlyList<string> Supported => (string[])s_supported.Clone();

    /// <summary>The well-known channel URI for the root channel.</summary>
    public const string RootResourceUri = "ahp-root://";
}
`;
}

// ─── Exhaustiveness ─────────────────────────────────────────────────────────

function collectEnumNames(project: Project): void {
  for (const name of [...STATE_ENUMS, ...COMMAND_ENUMS, ...NOTIFICATION_ENUMS, 'ActionType']) {
    ALL_ENUM_NAMES.add(name);
  }
  // ChildCustomizationType is aliased to CustomizationType (already counted).
  void project;
}

function checkExhaustiveness(project: Project): void {
  const protocolModules = ['state.ts', 'actions.ts', 'commands.ts', 'notifications.ts', 'errors.ts'];
  const imported = new Set<string>();
  for (const baseName of protocolModules) {
    for (const sf of findProtocolSourceFiles(project, baseName)) {
      for (const decl of sf.getInterfaces()) {
        if (decl.isExported()) imported.add(decl.getName());
      }
      for (const decl of sf.getTypeAliases()) {
        if (decl.isExported()) imported.add(decl.getName());
      }
    }
  }

  const coveredByLists = new Set<string>([
    ...STATE_STRUCTS.map((s) => s.name),
    ...STATE_ENUMS,
    ...COMMAND_STRUCTS.map((s) => s.name),
    ...COMMAND_ENUMS,
    ...NOTIFICATION_STRUCTS,
    ...NOTIFICATION_ENUMS,
    ...ACTION_VARIANTS.filter((v) => v.tsInterface !== '_merged_').map((v) => v.tsInterface),
  ]);

  const knownSpecial = new Set<string>([
    'URI', 'BaseParams', 'StringOrMarkdown', 'ToolCallState', 'StateAction',
    'ActionEnvelope', 'ActionOrigin', 'ResponsePart', 'ToolResultContent',
    'SessionToolCallApprovedAction', 'SessionToolCallDeniedAction',
    'SessionToolCallConfirmedAction', 'PingParams', 'TerminalClaim',
    'TerminalContentPart', 'SessionInputQuestion', 'SessionInputAnswerValue',
    'SessionInputAnswer', 'MessageAttachment', 'MessageAttachmentBase',
    'Customization', 'ChildCustomization', 'ChildCustomizationType',
    'CustomizationLoadState', 'ReconnectResult', 'AuthRequiredErrorData',
    'PermissionDeniedErrorData', 'UnsupportedProtocolVersionErrorData',
    'AhpError', 'AhpErrorDetailsMap', 'AhpErrorCode', 'AhpErrorCodeWithData',
    'JsonRpcErrorCode', 'ChangesetOperationTarget',
  ]);

  const missing = [...imported].filter((n) => !coveredByLists.has(n) && !knownSpecial.has(n));
  if (missing.length > 0) {
    console.warn(
      'generate-csharp.ts exhaustiveness: the following types are exported from ' +
        'the protocol source modules but not covered by the C# generator:\n' +
        missing.map((n) => `  - ${n}`).join('\n'),
    );
  }
}

// ─── Main Entry Point ────────────────────────────────────────────────────────

export function generateCSharpPackage(project: Project, outputDir: string): void {
  collectEnumNames(project);
  checkExhaustiveness(project);

  const srcDir = path.join(outputDir, 'src', 'AgentHostProtocol.Abstractions', 'Generated');
  fs.mkdirSync(srcDir, { recursive: true });

  fs.writeFileSync(path.join(srcDir, 'State.generated.cs'), generateStateFile(project));
  fs.writeFileSync(path.join(srcDir, 'Actions.generated.cs'), generateActionsFile(project));
  fs.writeFileSync(path.join(srcDir, 'Commands.generated.cs'), generateCommandsFile(project));
  fs.writeFileSync(path.join(srcDir, 'Notifications.generated.cs'), generateNotificationsFile(project));
  fs.writeFileSync(path.join(srcDir, 'Errors.generated.cs'), generateErrorsFile());
  fs.writeFileSync(path.join(srcDir, 'Messages.generated.cs'), generateMessagesFile());
  fs.writeFileSync(path.join(srcDir, 'Version.generated.cs'), generateVersionFile(project));
}
