/**
 * Verify generated output freshness — mechanically enforces that the committed
 * per-language telemetry-name holders are "identical by construction" to what
 * the generators emit RIGHT NOW from `types/telemetry/registry.ts`.
 *
 * Why a runtime gate on top of the per-language `git diff` drift checks in
 * `ci.yml`: the git-diff checks only fire inside the CI job that runs the
 * matching `generate:<lang>` step, and they depend on a clean git tree. This
 * script regenerates the holders and compares the committed bytes against the
 * freshly-generated bytes WITHOUT depending on git, so the same "did you forget
 * to regenerate?" guard runs from a plain `npm test` on any contributor's
 * machine. It pairs with `verify-changelog.ts` / `verify-release-metadata.ts`
 * as a third "no stale committed artifact" gate.
 *
 * Mechanism: the generators write in place. For each holder this script checks,
 * it snapshots the committed bytes, runs the owning `generate:<lang>` entry
 * point, reads the regenerated bytes, then ALWAYS restores the snapshot (so the
 * gate is non-destructive even when it finds drift — the working tree is left
 * exactly as it was found). Regeneration is deterministic and the rest of the
 * tree is already in sync (CI's drift checks guarantee that), so regenerating
 * to compare a holder leaves every other file byte-identical.
 *
 * Run via `npm run verify:generated` (also wired into `npm test`).
 */

import { execFileSync } from 'child_process';
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, '..');

/** A committed generated holder + the generate script that produces it. */
interface GeneratedHolder {
  /** Human label for failure output. */
  readonly label: string;
  /** Path (relative to ROOT) of the committed generated file. */
  readonly file: string;
  /** `package.json` script (`npm run <generate>`) that regenerates it. */
  readonly generate: string;
}

/**
 * The committed cross-client telemetry-name holders. Each is generated from
 * `types/telemetry/registry.ts`; the TypeScript holder is intentionally absent
 * because it is a gitignored build artifact (regenerated at publish), not a
 * committed source.
 */
const HOLDERS: readonly GeneratedHolder[] = [
  {
    label: 'go',
    file: 'clients/go/ahptypes/telemetry.generated.go',
    generate: 'generate:go',
  },
  {
    label: 'rust',
    file: 'clients/rust/crates/ahp-types/src/telemetry.rs',
    generate: 'generate:rust',
  },
  {
    label: 'kotlin',
    file: 'clients/kotlin/src/main/kotlin/com/microsoft/agenthostprotocol/generated/Telemetry.generated.kt',
    generate: 'generate:kotlin',
  },
  {
    label: 'swift',
    file: 'clients/swift/AgentHostProtocol/Sources/AgentHostProtocol/Generated/Telemetry.generated.swift',
    generate: 'generate:swift',
  },
];

function runGenerate(script: string): void {
  // `--allow-missing-formatter` keeps the Rust/Go generators from failing when
  // rustfmt/gofmt is absent; the committed holders are already formatted, so a
  // missing formatter must not turn this freshness gate into a false negative.
  execFileSync('npm', ['run', script, '--', '--allow-missing-formatter'], {
    cwd: ROOT,
    stdio: 'pipe',
  });
}

function main(): void {
  const drifted: { holder: GeneratedHolder }[] = [];

  // Group holders by the generate script so we run each generator once.
  const byScript = new Map<string, GeneratedHolder[]>();
  for (const holder of HOLDERS) {
    const list = byScript.get(holder.generate) ?? [];
    list.push(holder);
    byScript.set(holder.generate, list);
  }

  for (const [script, holders] of byScript) {
    // Snapshot the committed bytes for every holder this generator owns.
    const snapshots = holders.map((holder) => {
      const abs = path.join(ROOT, holder.file);
      if (!fs.existsSync(abs)) {
        throw new Error(`verify-generated: committed holder is missing: ${holder.file}`);
      }
      return { holder, abs, committed: fs.readFileSync(abs) };
    });

    try {
      runGenerate(script);
      for (const { holder, abs, committed } of snapshots) {
        const regenerated = fs.readFileSync(abs);
        if (!committed.equals(regenerated)) {
          drifted.push({ holder });
        }
      }
    } finally {
      // Always restore the committed bytes — the gate never mutates the tree,
      // whether it passed or found drift.
      for (const { abs, committed } of snapshots) {
        fs.writeFileSync(abs, committed);
      }
    }
  }

  if (drifted.length > 0) {
    console.error('❌ Generated-output freshness check failed:');
    for (const { holder } of drifted) {
      console.error(
        `  [${holder.label}] ${holder.file} is stale — it does not match the ` +
          `output of 'npm run ${holder.generate}'.`,
      );
    }
    console.error(
      "  hint: run 'npm run generate' and commit the regenerated holders. " +
        'The telemetry holders are generated from types/telemetry/registry.ts; ' +
        'edit the registry, not the holders.',
    );
    process.exit(1);
  }

  console.log(
    `✅ Generated-output freshness check passed for: ${HOLDERS.map((h) => h.label).join(', ')}`,
  );
}

main();
